### PR TITLE
ADD composer.json

### PR DESCRIPTION
**Pull request by michaelmeneses**

### CODE REVIEW

**Comment by michaelmeneses** [comment]
Hi @michael-milette,
Adding composer.json you can manage plugin dependencies using PHP COMPOSER.

**Comment by michael-milette** [comment]
Hi @michaelmeneses , thank you very kindly for your contribution. Your effort is much appreciated. I have been giving your proposal a lot of thought. I have a couple of questions for you and am open to hearing more.  Could you please give me an example of how this might be useful? Also, which plugin dependency are you referring to?

**Comment by michaelmeneses** [comment]
Hi @michael-milette,

You can add **michael-milette/moodle-local_mailtest** as require in **MOODLE/composer.json**. Running the "composer update" command and COMPOSER (https://getcomposer.org/) will install the plugin in **MOODLE/local/**.

See my project at https://github.com/michaelmeneses/moodle-composer (only Linux for now). Here we use ROOT/MOODLE/. So you do not have to change anything in Moodle, not even MOODLE/composer.json. 

I maintain a repository of plugins using SATIS (https://satis.middag.com.br/). I'm working to improve it.

I use this solution on my servers, clients and the BRAZIL NATIONAL SCHOOL OF PUBLIC ADMINISTRATION (http://www.enap.gov.br/) even with Jenkins.

Thank you.

**Comment by michaelmeneses** [comment]
Hi @michael-milette. You can resolve this PR?

**Comment by michael-milette** [comment]
Hi @michaelmeneses, I am still considering your PR. This is non-standard. Can you give some examples of other plugins that include a composer.json?

**Pull request merged**
